### ISSUE TITLE
Firewall cookbook cannot be used in LWRPs

### ISSUE THREAD

**Issue by jochenseeber** [chef-cookbooks/firewall#108]
The cookbook looks up the firewall in the current run context:

    firewall = run_context.resource_collection.find(firewall: new_resource.firewall_name)

However, inside a LWRP, we're not in the same run context as the main recipe, so the firewall resource cannot be found. It also doesn't help defining a new firewall resource in the LWRP, because then we have multiple firewall resources, one per run context, stomping on each others feet.

This really narrows the field of application for this cookbook.

**Comment by martinb3** [comment]
Hello! While one option would be to [disable `use_inline_resources`](https://docs.chef.io/custom_resources.html#use-inline-resources), I'm not sure there's a nice general solution for this.

I've actually got a branch that removes this lookup, and allows the firewall resource to do the lookups, but it _still_ won't see any firewall_rules declared inside a run_context it can't see.

I don't think it makes sense to have two firewalls in different resource collections that can work together (it feels weird given the object model), but I'd be open to suggestions for changes to make this work better.

Maybe we could have a way to pass in an additional run_context? Or allow you to add firewall_rule resources to a node attribute where firewall can find them? Just brainstorming at this point.

**Comment by jochenseeber** [comment]
I don't think disabling use_inline_resources is possible with the new Chef 12.5 LWRPs. How about walking up the run_context hierarchy using ResourceContext#parent_run_context and using the first firewall we find?

**Comment by martinb3** [comment]
I could try that -- in fact, I like that idea. But I was under the impression that there was no guarantee one would exist -- that we'd be relying on something that wasn't part of the 'public API', so to speak. If I make that change, do you have an easy way to test it with your LWRP?

**Comment by jochenseeber** [comment]
No problem, I'd be happy to.

**Comment by martinb3** [comment]
@jochenseeber For what it's worth, they've changed the default for `use_inline_resources` in 12.5 to be `true`, but it's still available from what I understand.

**Comment by martinb3** [comment]
Could you try that first and let us know if that works? We have a refactoring branch that centralizes a lot of the logic into the firewall resource, where it wouldn't be able to search through child resource collections, in this example.

**Comment by martinb3** [comment]
Hello! I'm going to close this after no update for a month, but please go ahead and try `use_inline_resources` and let us know.

**Comment by rmoriz** [comment]
Having the same issue using an LWRP with chef-client 12.6.x and `use_inline_resources`

Example:

```yaml
    run_list:
      - recipe[org-base]   # includes recipe that executes: firewall 'default' 
      - recipe[org-nginx]  # includes recipe that calls the LWPR, code below
```

libraries/provider.rb
```ruby

require 'chef/dsl/include_recipe'

class Chef
  class Provider
    # see https://github.com/chef/chef/issues/2366
    # and https://github.com/chef/chef/commit/e4c52e53a4b9caebebf09fb8ff944f7a2397fe33
    include Chef::DSL::IncludeRecipe
  end
end
```

`providers/nginx.rb`


```ruby
use_inline_resources

def whyrun_supported?
  true
end

action :install do
  version = new_resource.version
  configure_firewall = new_resource.configure_firewall
  firewall_allow_ports = new_resource.firewall_allow_ports # default: [80,443]

  service 'nginx'

  firewall_rule 'nginx' do
    protocol :tcp
    port firewall_allow_ports
    command :allow
    action :create
    only_if { configure_firewall }
  end
…
```

error:

````

    Chef::Exceptions::ResourceNotFound
    ----------------------------------
    firewall_rule[nginx] (…/providers/nginx.rb line 16) had an error: Chef::Exceptions::ResourceNotFound: Cannot find a resource matching firewall[default] (did you define it first?)
```

**Comment by martinb3** [comment]
Hello! You're actually asking for this behavior by setting `use_inline_resources`, e.g. "Converge everything inside a subcontext and don't look at the parent one." This is a reason for turning `use_inline_resources` off or inserting your firewall_rule into the top level run context (`Chef.run_context`). The DSL is a bit clunky for this, so you'll want to use Ruby, if you don't want to turn off `use_inline_resources`.

**Comment by rmoriz** [comment]
Chef 12.10 introduced some nice DSL sugar: https://docs.chef.io/dsl_recipe.html#find-resource
