### ISSUE TITLE
Unable to rate limit with ufw

### ISSUE THREAD

**Issue by rbugajewski** [chef-cookbooks/firewall#113]
The cookbook doesn’t support the `limit` command, so that you can’t rate limit connections, e. g. a simple `ufw limit 22/tcp` won’t work. The `raw` parameter is only used for other firewalls.

The `firewall` cookbook should support this kind of rule.

**Comment by martinb3** [comment]
Hello! It sounds like there are two issues -- missing limit as well as unsupported `raw` attribute on ufw. Thank you for reporting this!

**Comment by martinb3** [comment]
Hello! Please try v2.3.1 where this should be resolved, so you can use the raw support to add this rule. Thank you!
