### ISSUE TITLE
How to use FirewallD on Ubuntu?

### ISSUE THREAD

**Issue by leshik** [chef-cookbooks/firewall#124]
Is it possible to use FirewallD on platforms other than rhel? I'd like to use FirewallD on Ubuntu. The package is available in repositories, but the cookbook seems to ignore it if platform is not rhel (firewall 'firewalld' configures ufw instead).

**Comment by martinb3** [comment]
Hello! The resource name is arbitrary -- `firewall 'firewalld'` just makes a chef resource named `firewalld`. You probably want to override the provider for the resource, e.g.:

```
firewall 'default' do
  provider Chef::Provider::FirewallFirewalld
end
```

Please be aware that Ubuntu often makes subtle changes when they implement things like this, so it's entirely possible that this cookbook won't work on Ubuntu with firewalld. But you're welcome to try or submit PRs to make it work better :+1: Thanks!
