### ISSUE TITLE
log_level attribute doesn't support off

### ISSUE THREAD

**Issue by leinster** [chef-cookbooks/firewall#129]
The `:log_level` attribute doesn't allow the value `:off`.

**Comment by martinb3** [comment]
Hi @leinster -- what firewall provider are you specifically trying to use? ufw?

**Comment by leinster** [comment]
Hi,
Yes, ufw - it's all working great so far, but I'd like to be able to disable logging. 
Thanks

**Comment by martinb3** [comment]
Added this to master as an allowed option of `:off`.

**Comment by leinster** [comment]
Thank you, just saw this was in.
