### ISSUE TITLE
Insecure by default?

### ISSUE THREAD

**Issue by rmoriz** [chef-cookbooks/firewall#132]
Hi,

It just happend to me that for whatever reason an attribute was empty, and hence  https://github.com/chef-cookbooks/firewall/blob/master/libraries/helpers_ufw.rb#L95-L99 opened up *everything*.

I think this is a very bad default.

(UFW on Debian Jessie)

**Comment by jaseeey** [comment]
It's been a while since I used and configured this, but I recall having the same issue where no DROP was added at the end of the chain by default on iptables. Is this something which should be handled?

**Comment by rmoriz** [comment]
No, it's not about a missing DROP,  the problem is in the lines I've linked to, which result:
`ufw allow in proto tcp to any from any`

**Comment by martinb3** [comment]
Hello! 

> It just happend to me that for whatever reason an attribute was empty

@rmoriz, can you show us the actual rule you're talking about? I'd like to understand all of the parameters you supplied, and what you didn't supply, and what the result was.

I'd like to see how odd the rule is, and figure out if it's something someone might want to do (not all images start with the firewall open, and someone might want to do this).

> I recall having the same issue where no DROP was added at the end of the chain by default on iptables

@jaseeey Indeed, this cookbook prefers to set the default chain policy to drop, vs. an allow policy by default, with a drop at the end. I believe it's an iptables best practice to have a default policy that performs some unaction on unmatched packets (order doesn't matter in the rules) vs. matching all remaining packets with a specific rule (drop must be last).

**Comment by rmoriz** [comment]
example cookbook code:

```ruby

node.default['example']['ports'] = [ nil ]


node['example']['ports'].each do |p|
  firewall_rule "autossh-fwd-tcp-#{p}" do
    protocol :tcp
    port p
    command :allow
    action :create
  end  
end

```

result:

```
       * file[/etc/default/ufw-chef.rules] action create
         - update content in file /etc/default/ufw-chef.rules from 9a4868 to 454e49
         --- /etc/default/ufw-chef.rules	2016-04-19 17:09:45.680002614 +0000
         +++ /etc/default/.chef-ufw-chef.rules20160419-3939-1c8pchs	2016-04-19 17:11:40.836008184 +0000
         @@ -16,4 +16,5 @@
          ufw allow in proto tcp to any port 1234,5000:5100,5678 from any
          ufw limit 23/tcp
          ufw allow in proto tcp to any port 5000:5100 from any
         +ufw allow in proto tcp to any from any
      
```

**Comment by rmoriz** [comment]
See example code: https://github.com/chef-cookbooks/firewall/compare/master...rmoriz:rmoriz/bug-example?expand=1

**Comment by martinb3** [comment]
I'm concerned if we disable this, we will remove the ability for people to open their firewall up.

**Comment by rmoriz** [comment]
introduce a truthy check, maybe?

```ruby
port true
```

to open everything up?

I doubt that there is any useful scenario of using this cookbook just to to disable it _in this way_, at least I would not tolerate such ugly hacks in my environments and would let people go for such crap 😈

**Comment by martinb3** [comment]
@rmoriz I've added a warning that is printed when a rule appears to be opening all traffic. Next time we bump major revisions, we can revisit adding a breaking change like `port true`. Thanks for reporting this!

**Comment by rmoriz** [comment]
Can we make this an error with the next minor versions?

**Comment by martinb3** [comment]
I believe it would violate semantic versioning to make a backwards incompatible change on a minor version bump.

**Comment by rmoriz** [comment]
I still believe this is a bug, not intentional behavior that any sane user relies on. Anyway: What would you suggest someone should do, who intentionally wants to open all ports?

**Comment by martinb3** [comment]
> What would you suggest someone should do, who intentionally wants to open all ports?

I'm not sure if you're intending this question to be rhetorical or not -- but I would expect them to use a firewall_rule that opens all ports by omitting any specific port.

**Comment by rmoriz** [comment]
> I'm not sure if you're intending this question to be rhetorical or not -- but I would expect them to use a firewall_rule that opens all ports by omitting any specific port.

That does not make sense to me. Given I've locked my doors and I want to hand over the keys for zero/nil doors, then I've handed out zero keys…

**Comment by martinb3** [comment]
Are you still encountering a problem with this cookbook, after fixing your original logic bug of giving a nil port? It feels like we disagree philosophically on what omitting a port does, but I can't tell if there's an actual technical problem here or just a disagreement on approach.
