### ISSUE TITLE
Rule Resources inside 12.5+ Dynamic Resources

### ISSUE THREAD

**Issue by bdwyertech** [chef-cookbooks/firewall#134]
### Cookbook version
2.5.0

### Chef-client version
12.8.1 & 12.9.38

### Platform Details
Ubuntu 12.04 & CentOS 7.2

### Scenario:
Attempting to use the firewall_rule resource from within a Chef 12.5+ dynamic resource.

### Steps to Reproduce:
Create a 12.5+ dynamic resource trying to make use of firewall_rule resource(s)

### Expected Result:
Create and instate defined firewall_rule resources

#### 12.8.1
```
==> default: [2016-04-27T12:11:32-04:00] ERROR: app_security[TEST] (org-firewall::default line 39) had an error: Chef::Exceptions::ResourceNotFound: firewall_rule[Allow BDWY (BD-MBPro - 192.168.50.1)] (/var/chef/cache/cookbooks/org-firewall/resources/app_security.rb line 79) had an error: Chef::Exceptions::ResourceNotFound: Cannot find a resource matching firewall[default] (did you define it first?)
```
This is likely due to looking only in the current `run_context` for the `firewall` resource to notify
https://github.com/chef-cookbooks/firewall/blob/master/libraries/provider_firewall_rule.rb#L26

#### 12.9.38
I believe this Chef version allows for notifications to resources defined in the parent run_context by making the find recursive. (https://github.com/chef/chef/pull/4741)
The resources fire, but the firewall rules aren't actually getting instated into iptables, I presume due to the firewall cookbook not being able to find the resources since they were defined inside a dynamic resource.

Maybe this could somehow be tweaked to facilitate parsing of `firewall_rule` resources created from within a 12.5+ dynamic resource?
https://github.com/chef-cookbooks/firewall/blob/master/libraries/provider_firewall_ufw.rb#L65

**Comment by martinb3** [comment]
Hello @bdwyertech! As [described here](https://github.com/chef/chef/issues/3123#issuecomment-174640392), can you inject your firewall rule resources into the top level run context? I believe that would solve your immediate issue. 

The problem with a recursive find is that the `firewall` resource does the find, not the `firewall_rule` resources. This is very useful since it allows us to make a single `firewall_rule` provider that works across all firewall implementations (it's basically just a container for data). Unfortunately, parent run contexts don't have a way to enumerate child run contexts, so there's no way for firewall providers to search for rules in nested run contexts.

**Comment by bdwyertech** [comment]
@martinb3  Give me a hint my friend;  I've been trying to do exactly that.  I've been trying to feed `run_context` a few different ways.

I was previously trying something like
```
firewall_rule 'Allow SSH' do
  port 22
  command :allow
  run_context Chef.run_context # => or run_context.parent_run_context, etc.
end
```

Is something like this more along the lines of what I should be doing?
```
Chef::Resource::FirewallRule.new('blah port 80', Chef.run_context).tap do |r|
  r.port 80
  r.command :allow
end
```

**Comment by martinb3** [comment]
I believe it's `run_context Chef.node.run_context` should work...

**Comment by bdwyertech** [comment]
Sweet, I think I managed to get it working with 12.9.38 at least...

```
declare_resource(:firewall_rule, "Test Rule", run_context: Chef.run_context) do
  port [123, 456]
  direction :in
  source '1.2.3.4'
  command :allow
  not_if { platform_family?('debian')}
end
```

**Comment by martinb3** [comment]
Great! I wish we had a better option for juggling the various run contexts, but I guess once you get into custom resources, you have to deal with all that... :+1:
