### ISSUE TITLE
port nil currently does not overwrite the value of port. This will change in Chef 13

### ISSUE THREAD

**Issue by stissot** [chef-cookbooks/firewall#135]
### Cookbook version
2.5.0

### Chef-client version
12.5.1

### Platform Details
Ubuntu 14.04.3

### Scenario:
Call `firewall_rule` with `port` set to nil to match "any port" will raise a warning, as the resource does not allows nil values for the `port` property.

### Steps to Reproduce:

Use a code like this in your recipe:
```
firewall_rule 'allow-icmp-switch.ch' do
    destination '130.59.138.57'
    protocol :icmp
    port nil
    direction :out
    command :allow
end
```

### Expected Result:
`-A OUTPUT -d 130.59.138.57 -p icmp -m comment --comment "allow-icmp-switch.ch" -j ACCEPT`

### Actual Result:
> Deprecated features used!
         port nil currently does not overwrite the value of port. This will change in Chef 13, and the value will be set to nil instead. Please change your code to explicitly accept nil using "property :port, [MyType, nil]", or stop setting this value to nil. at 1 location:

**Comment by martinb3** [comment]
Hello there! If you don't want to specify a port value, you should simply omit port as a parameter. Can you give that a try and let us know? Thanks!

**Comment by martinb3** [comment]
Let us know if you still encounter this issue. Thanks!

**Comment by stissot** [comment]
> Hello there! If you don't want to specify a port value, you should simply omit port as a parameter. Can you give that a try and let us know? Thanks!

It indeed works if the port attribute is omitted, but it is not suitable in my code, as the resource is called in a loop of rules, some who require a port, some not. Since nil is the default value of the port parameter, I think the resource should also accept a nil value for it.

**Comment by martinb3** [comment]
Hello! I think the deprecation warning is aimed at cookbooks who don't use a default value of `nil` -- so actually when Chef 13 is released, the firewall cookbook will still work correctly. According to https://github.com/chef/chef/issues/3197, in the mean time, you should do something like this:
```
firewall_rule 'foo' do
  port foo unless foo.nil?
end
```

I think that would solve the deprecation warning and allow you to omit passing a port when it's not needed. Is that an acceptable solution for you @stissot?

**Comment by martinb3** [comment]
Also, for what it's worth, I think they were aiming to remove this particular case (where nil was the default, and you're also passing nil) via https://github.com/chef/chef/pull/4296.

**Comment by stissot** [comment]
@martinb3 the `port foo unless foo.nil?` prevents the warning, thank you
