### ISSUE TITLE
Disabling firewall errors on repeated converges

### ISSUE THREAD

**Issue by edwardbartholomew** [chef-cookbooks/firewall#140]
### Cookbook version
2.5.1 - Also 2.5.0 but those are only two versions I tried. 

### Chef-client version
12.10.24

### Platform Details
CentOS Linux release 7.2.1511 (Core)

### Scenario:
Disable firewall (firewalld in CentOS 7)

### Steps to Reproduce:
Below is in my recipe. Running once, results in firewalld being disabled and stopped. Running a second time, results in an error. 
firewall 'default' do
  action :disable
end

### Expected Result:
I run the cookbook once and firewalld is disabled and stopped. Running the cookbook a second time, no changes should happen. 

### Actual Result:
When I run the cookbook a second time, it errors because firewalld is already disabled. 
<script src="https://gist.github.com/edwardbartholomew/11e693c1941b4ccf94a01af9f8263a45.js"></script>

**Comment by edwardbartholomew** [comment]
Oops here are my converge logs:
https://gist.github.com/edwardbartholomew/11e693c1941b4ccf94a01af9f8263a45

**Comment by martinb3** [comment]
Hello! Would you be willing to give the current master branch a try and let us know if that resolves your issue? Thank you!

**Comment by edwardbartholomew** [comment]
Thank you, i will test tonight and update. Appreciate your help.

**Comment by edwardbartholomew** [comment]
Worked great @martinb3 , thank you so much! firewalld was disabled and stopped during first converge, and then during second no changes and successful convergence.
       Recipe: mybaseconfig::firewall
         * firewall[default] action disable (up to date)
         * service[firewalld] action disable (up to date)
         * service[firewalld] action stop (up to date)
         * file[create empty /etc/sysconfig/firewalld-chef.rules] action create (up to date)

**Comment by martinb3** [comment]
Great! I'll do a release shortly.

**Comment by edwardbartholomew** [comment]
thanks again! 👍
