### ISSUE TITLE
ruleset problems w/ hash keys

### ISSUE THREAD

**Issue by jwmarshall** [chef-cookbooks/firewall#143]
### Cookbook version
2.5.2

### Chef-client version
12.6.0

### Platform Details
Ubuntu 14.04

### Scenario:
Apply nat filter ruleset using the provided example results in missing rules where keys overlap.

### Steps to Reproduce:
Use provided example:

```
node.default['firewall']['iptables']['defaults'][:ruleset] = {
  '*filter' => 1,
  ':INPUT DROP' => 2,
  ':FORWARD DROP' => 3,
  ':OUTPUT ACCEPT' => 4,
  'COMMIT_FILTER' => 100,
  '*nat' => 101,
  ':PREROUTING DROP' => 102,
  ':POSTROUTING DROP' => 103,
  ':OUTPUT ACCEPT' => 104,
  'COMMIT_NAT' => 200
}
```

### Expected Result:

```
# position 1
*filter
# position 2
:INPUT DROP
# position 3
:FORWARD DROP
# position 4
:OUTPUT ACCEPT
# position 50
-A INPUT -p tcp -m tcp -m multiport --dports 22 -m comment --comment "allow world to ssh" -j ACCEPT
-A INPUT -m state --state RELATED,ESTABLISHED -m comment --comment "established" -j ACCEPT
# position 100
COMMIT
# position 101
*nat
# position 102
:PREROUTING DROP
# position 103
:POSTROUTING DROP
# position 104
:OUTPUT ACCEPT
# position 200
COMMIT
```

### Actual Result:

Note `:OUTPUT ACCEPT` on position 4 is missing as it was replaced by the key `:OUTPUT ACCEPT` in position 104. Perhaps we could nest the chains for tables `*filter` and `*nat` to remedy this? 
```
# position 1
*filter
# position 2
:INPUT DROP
# position 3
:FORWARD DROP
# position 50
-A INPUT -p tcp -m tcp -m multiport --dports 22 -m comment --comment "allow world to ssh" -j ACCEPT
-A INPUT -m state --state RELATED,ESTABLISHED -m comment --comment "established" -j ACCEPT
# position 100
COMMIT
# position 101
*nat
# position 102
:PREROUTING DROP
# position 103
:POSTROUTING DROP
# position 104
:OUTPUT ACCEPT
# position 200
COMMIT
```

**Comment by jwmarshall** [comment]
It looks like placing a space after the hash key is a possible fix for the current situation. I think it would be more ideal if the ruleset attribute looked like this. Of course this introduces some additional issues/headaches since the table name does not have a defined position anymore.

```
node.default['firewall']['iptables']['defaults'][:ruleset] = {
  '*filter' => {
    ':INPUT DROP' => 2,
    ':FORWARD DROP' => 3,
    ':OUTPUT ACCEPT' => 4
  }
  '*nat' => {
    ':PREROUTING DROP' => 102,
    ':POSTROUTING DROP' => 103,
    ':OUTPUT ACCEPT' => 104
  }
}
```

**Comment by martinb3** [comment]
I originally tried nesting, but with the way chef merges hashes from default precedence to other levels, it made it very difficult to force an override on everything. Perhaps as a workaround, you could try something like:

```
node.default['firewall']['iptables']['defaults'][:ruleset] = {
  '*filter' => 1,
  ':INPUT DROP' => 2,
  ':FORWARD DROP' => 3,
  ':OUTPUT ACCEPT # foo' => 4,
  'COMMIT_FILTER' => 100,
  '*nat' => 101,
  ':PREROUTING DROP' => 102,
  ':POSTROUTING DROP' => 103,
  ':OUTPUT ACCEPT # bar' => 104,
  'COMMIT_NAT' => 200
}
```

We had this same issue with `COMMIT` -- perhaps I need to implement the same exclusions for OUTPUT/INPUT/POSTROUTING/PREROUTING? This is really starting to become a nasty workaround, but I don't really love the chef attribute precedence issues either.

**Comment by jgoldschrafe** [comment]
At the very least, the documentation should really be updated, since the example in no way produces a working configuration.

**Comment by martinb3** [comment]
I agree; it's a workaround at best, and the example docs need updating.

**Comment by martinb3** [comment]
Hi there -- I've shipped some additional docs and fixed the example. Thank you!
