### ISSUE TITLE
Not reseting the firewall

### ISSUE THREAD

**Issue by montge** [chef-cookbooks/firewall#146]
### Cookbook version
2.5.2

### Chef-client version
12.12.15

### Platform Details
Redhat Linux 7.2

### Scenario:
I'm trying to NOT reset the firewall on the machine, rather just add rules to an existing machine.  It's not clear from documentation on how to handle this.  Do we do something other then firewall 'default'?

### Steps to Reproduce:
add to attributes default.rb, the ssh rules
add to recipe default.rb,
firewall 'default' do with save
firewall_rule 'random_application' port x, command: allow

### Expected Result:
I expect it to leave the existing firewall set alone and add onto the existing firewall.

### Actual Result:
it disables existing rules such as port 22 and icmp, as well as any other rulesets.

**Comment by montge** [comment]
I think what is going on is in lines 57-58 it's telling the firewall-cmd to remove all the rules.  Not what I would expect.  I would expect it to save everything that is in the firewall as permanent (maybe) and then going forward.  Only :flush should actually remove the firewall rules.

https://github.com/chef-cookbooks/firewall/blob/master/libraries/helpers_firewalld.rb

**Comment by martinb3** [comment]
Hi there -- we designed this cookbook to be declarative, i.e. the rules you declare are the rules you will get. Most folks using this cookbook will expect if, e.g. they don't declare a `firewall_rule` for port 22, that the rule is removed from the machine and will not exist after chef executes. This is similar to how chef manages an _entire file_ but rarely manages only part of a file. I hope this helps explain...

**Comment by montge** [comment]
Make sense, unfortunately it's not what we need since we have different parties submitting configuration items to our environment.  Sounds like the best option is to either branch this.

**Comment by martinb3** [comment]
> A question, it seems like theoretically you could setup a structure where each app has variables for it's ports, and then have a cookbook that looks for those.

Yes, it's a very common pattern to pass around data in chef to build a complete ruleset from different recipes or cookbooks (that represent different apps).

> Sounds like the best option is to either branch this or do something static.

For some of the firewall implementations (maybe ufw or firewalld), there might be a way to have a `rules.d` directory and have chef only manage the rules it's aware of, but I think it's probably a nightmare to manage for iptables. I'm not sure which underlying firewall you're using, but it might offer a way to just drop a file into a directory to do this.

Hope this helps!
