### ISSUE TITLE
firewalld and reboot

### ISSUE THREAD

**Issue by safematix** [chef-cookbooks/firewall#147]
### Cookbook version
firewall               2.5.2

### Chef-client version
12.13.15

### Platform Details
Red Hat Enterprise Linux Server release 7.2 (Maipo)

### Scenario:

At the first chef run, the firewall settings will be set correct. After a reboot, the settings will not load!

### Steps to Reproduce:
Use in your cookbook:

```chef
firewall 'default' do
  action :install
end

firewall_rule 'ssh' do
  port     22
  command  :allow
end
```
Make a chef run and reboot the node.

### Expected Result:
The firewalld settings will load after reboot.

### Actual Result:
The firewalld settings not loading after reboot.

**Comment by martinb3** [comment]
Hi there -- firewalld has the concept of `permanent` and non-permanent rules. My understanding is that, by default, rules are added as non-permanent in firewalld.

You can use the save action on the firewall resource if you want to save existing rules:
> `:save`: Ensure all rules are added permanently under firewalld using --permanent. Not supported on ufw, iptables. You must notify this action at the end of the chef run if you want permanent firewalld rules (they are not persistent by default).

We've also noted in this in the readme:

`default['firewall']['firewalld']['permanent'] = false`, set to true if you want firewalld rules to be added with --permanent so they survive a reboot. This will be changed to true by default in a future major version release.

Does that help?

**Comment by safematix** [comment]
Hi,

yes, that helps a lot.

My mistake. :(

I will close this now.

Thanks
