### ISSUE TITLE
Release please

### ISSUE THREAD

**Issue by axos88** [chef-cookbooks/firewall#157]
A critical bug concerning service names on windows has been fixed. Please release a patch version so that we can use it.

https://github.com/chef-cookbooks/firewall/commit/dd39b95a712234fcbcd6db053fde3ced6186db2d#diff-836805b7b36b8449cb3588e8b8eb3fc0R63

Thanks,

**Comment by martinb3** [comment]
@axos88 That change was made in July, and our last release was October. The fix should already be available. /CC @snkutlu

**Comment by axos88** [comment]
It doesn't seem that way: https://github.com/chef-cookbooks/firewall/blob/v2.5.3/libraries/helpers_windows.rb#L63

**Comment by martinb3** [comment]
Ah, I see -- it's dated July 20th, but wasn't merged until later in October. 👍

**Comment by martinb3** [comment]
I've released v2.5.4. Thank you for the ping! :)
