### ISSUE TITLE
Default iptables rules block traffic on local interface.

### ISSUE THREAD

**Issue by jan0sch** [chef-cookbooks/firewall#158]
We just noticed that the default rules for iptables seem to block local traffic. This could be repaired using a simple rule like this:

```
firewall_rule "allow traffic on local interface" do
  interface 'lo'
  protocol :none
  command :allow
end
```

Should I create a pull request to include this in the cookbook?

**Comment by iennae** [comment]
Are you using the default recipe in this cookbook?

**Comment by jan0sch** [comment]
We're using the default recipe.

**Comment by martinb3** [comment]
Hi @jan0sch -- I assume this is with iptables, where loopback isn't allowed by default? I'm wondering if we should apply these kinds of defaults to iptables, firewalld, or both. Ideally, we would need to bump the major version as part of this, so no one is surprised by the new, slightly more open rule.

**Comment by jan0sch** [comment]
I think this is the case with iptables. I remember explicitely allowing loopback traffic in all iptables scripts back in the day.

**Comment by bdwyertech** [comment]
It's ICMP as well, I've got a little blimp I put in my wrapper recipe for this to give parity to UFW
```ruby
if platform_family?('rhel')
  firewall_rule 'Allow Localhost' do
    interface 'lo'
    protocol :none
    command :allow
  end

  firewall_rule 'Allow ICMP' do
    protocol :icmp
    command :allow
  end
end
```

**Comment by martinb3** [comment]
Hi @jan0sch -- could you give master a try and see if it's what you're looking for? Thanks!
