### ISSUE TITLE
Chef 13

### ISSUE THREAD

**Issue by bdwyertech** [chef-cookbooks/firewall#159]
Quick glance tells me we're broken here, looks like the delayed notify for application at the end of the run isn't firing.

Running `13.0.113` with `kitchen-dokken`

If I get a minute to skim through whatever changes were made, I'll see if I can fix it.

**Comment by Silaena** [comment]
There is definitely a concern regarding resource cloning that was removed from v13 of the chef client.

Below is an example of what was being thrown in v12.19.36 of the chef client.
`Deprecated features used!
         Cloning resource attributes for service[firewalld] from prior resource
       Previous service[firewalld]: /tmp/kitchen/cache/cookbooks/firewall/libraries/provider_firewall_firewalld.rb:39:in `block (2 levels) in <class:FirewallFirewalld>'
       Current  service[firewalld]: /tmp/kitchen/cache/cookbooks/firewall/libraries/provider_firewall_firewalld.rb:93:in `block in <class:FirewallFirewalld>' at 1 location:
           - /tmp/kitchen/cache/cookbooks/firewall/libraries/provider_firewall_firewalld.rb:93:in `block in <class:FirewallFirewalld>'
          See https://docs.chef.io/deprecations_resource_cloning.html for further details.`

**Comment by martinb3** [comment]
This looks like a pretty easy one to fix -- separate actions are using the same `service[firewalld]` resource, but when they're run together, they end up cloning the resource instead.

**Comment by martinb3** [comment]
@bdwyertech @Silaena could you give the current `chef13` branch a try? I think I fixed everything except an issue on Windows -- https://github.com/chef/chef/issues/6062.

**Comment by martinb3** [comment]
I believe we've resolved this. Please ping and we can re-open if not 👍

**Comment by bdwyertech** [comment]
Looks good @martinb3, all of my wrapper cookbook tests passed --- So this means the next release of this will be for Chef 13+ only eh?  I didn't have time to fork again and edit the metadata and test with a different chef version in the metadata.

**Comment by martinb3** [comment]
@bdwyertech great! thanks for testing.

The only thing restricting this to Chef 13.x will be the metadata; AFAIK, everything I've done here is also compatible with Chef 12.x.***

***Chef 12.x has so many breaking changes through 12.1 - 12.5 that testing all of the variations on Chef 12.x is a huge pain. I'd love to drop those, and just shift folks to use the older cookbook or Chef 13.x on the more recent version.
