### ISSUE TITLE
Add option to whitelist IPs and purge rules by port

### ISSUE THREAD

**Issue by jpSimkins** [chef-cookbooks/firewall#168]
Hello,

Thanks for this cookbook. I am new to chef but I found this very useful. 

One thing I am finding it difficult to do, or at least more work than needed, is whitelisting IPs. I currently build a databag that holds this information then I need to flush all rules for a specified port (22) and then I loop over the whitelist and apply it. This seems essential to a firewall system so I thought I'd make note of it.

I think an attribute would be useful for this:
```
default['firewall']['ip_whitelist'] = []
```

Also, a simple command with `firewall_rule` to remove any rules for a specified port would be very useful. I am not sure how to do this currently so I find it difficult to ensure that removed IPs are actually removed. I am still working on my own cookbook for this.

Something like this would be very useful:
```
firewall_rule 'purge current ssh rules' do
  port     22
  command  :purge
end
```

**Comment by martinb3** [comment]
Hi there -- we've designed this very deliberately as a library cookbook, and only provide the most basic of recipes. You're welcome to implement some of these ideas in your wrapper cookbook, but I'd like to avoid maintaining more attributes/logic in the recipes.

Regarding your idea for a purge command, we do offer the ability to clear the entire list of rules, but we're avoiding parsing firewall rules for content -- and we'd have to (in your example) parse pretty extensively (we'd have to catch port ranges, lists of ports, etc..) just to catch all the cases where port 22 is mentioned, and we'd have to do it across 3 different syntaxes (ufw, iptables, firewalld). We've gotten away from string parsing the firewall, and I don't think we want to go back in that direction.

Thanks for the feedback -- we appreciate it!
