### ISSUE TITLE
Append additional rules in second chef run

### ISSUE THREAD

**Issue by pvandervelde** [chef-cookbooks/firewall#184]
### Cookbook version
firewall 2.6.2

### Chef-client version
chef-solo 13.1.31

### Platform Details
Ubuntu 16.04

### Scenario:
I'm making VM images with [Packer](https://packer.io) from a base image. The base image was created by installing the Ubuntu 16.04 ISO on a VM HDD and then using Chef to install some base applications, amongst which a base configuration of the firewall (using the chef firewall cookbook). This works as expected, the base image has the firewall enabled with a number of rules for the base applications.

I then use the base image to create the final image by installing some image specific applications which requires updating the firewall. At this point all the existing rules are removed and only the new ones exist (somewhat expected but undesired) as shown here:

    * firewall[default] action restart
      * file[/etc/default/ufw-chef.rules] action create
        - update content in file /etc/default/ufw-chef.rules from 9f477c to 643aef
        --- /etc/default/ufw-chef.rules      2018-01-08 07:08:20.056227959 +0000
        +++ /etc/default/.chef-ufw-chef20180108-1068-1pj4asu.rules   2018-01-08 09:03:26.688590800 +0000
        @@ -1,12 +1,3 @@
         # position 50
        -ufw allow in proto tcp to any port 22 from any
        -ufw allow in proto tcp to any port 8500 from any
        -ufw allow in proto udp to any port 8600 from any
        -ufw allow in proto tcp to any port 8300 from any
        -ufw allow in proto tcp to any port 8301 from any
        -ufw allow in proto udp to any port 8301 from any
        -ufw allow in proto tcp to any port 8302 from any
        -ufw allow in proto udp to any port 8302 from any
        -ufw allow in proto udp to any port 53 from any
        -ufw allow in proto tcp to any port 53 from any
        +ufw allow in proto tcp to any port 3000 from any

So I guess the questions is would it be possible to have the firewall cookbook append the rules and not delete the existing ones.

**Comment by martinb3** [comment]
Hi there -- this cookbook doesn't have a mode where it ignores rules that don't have matching Chef rules. It's designed to manage the entire firewall as one resource, not really individual rules. Sorry!
