### ISSUE TITLE
 undefined method `include?' for :create:Symbol

### ISSUE THREAD

**Issue by gr790** [chef-cookbooks/firewall#188]
Hello, 

Any Help ?

Regards,
Rahul.

### Cookbook version
I have below entry in my Berksfile.
cookbook 'firewall', '~> 2.6.3'

### Chef-client version
I am using chef Gem, and below is my bundle list.
* chef (12.3.0)
  * chef-config (12.21.31)
  * chef-sugar (4.0.0)
  * chef-zero (4.9.0)

### Platform Details
It is RHEL 7.4 and it is VM.

### Scenario:
I am trying to setup firewalld on my virtual machine, till now iptables is working fine, but I want to migrate to firewalld.

### Steps to Reproduce:
I have this recipe which is mentioned in README.
```
firewall_rule '100-all_on_localhost' do
  interface 'lo'
  command :allow
  only_if { node['firewall']['allow_loopback'] }
end

firewall_rule 'ssh' do
  port 22
  command :allow
  only_if { node['firewall']['allow_ssh'] }
end

firewall 'default' do
  action :install
end
```

### Expected Result:
I guess it should run fine.

### Actual Result:
I run the recipe and it results into failure with below message.
`chef failed: firewall[default] had an error: NoMethodError: undefined method `include?' for :create:Symbol
`

**Comment by martinb3** [comment]
Hi there -- Chef 12.4.x or greater [is required](https://github.com/chef-cookbooks/firewall#requirements). There's some breaking changes with how actions and arrays of actions were handled before Chef 12.4.x and 12.5.x.

**Comment by gr790** [comment]
Hello,

Thanks, I updated chef to 12.5+, but do you think if you could add it as dependency in gemspec file.

Rahul.

**Comment by martinb3** [comment]
What Gemspec file, @gr790? It's already been declared in [the cookbook metadata](https://github.com/chef-cookbooks/firewall/blob/master/metadata.rb#L18) as 12.5 and greater.

**Comment by gr790** [comment]
Hello,

I thought it is gem. My bad.I guess updating cookbook using Berks should work like, how bundle works with Gemfile..Checking dependency.

I have one more question, do you think we should have IP version flag in firewal_rule to decide ipv4 or ipv6.

Regards,
Rahul.

**Comment by martinb3** [comment]
No worries :) Honestly, there's a lot of work still to be done for IPv6 support -- I'm torn if it's worth trying to make rules work for both, or have separate rules or a flag to determine which applies. The syntax / considerations start to get really different with more complex rules...
