### ISSUE TITLE
Firewall_rules resource not idempotent

### ISSUE THREAD

**Issue by DeWaRs1206** [chef-cookbooks/firewall#210]
### Cookbook version
2.7.0

### Chef-client version
14.10.9

### Platform Details
Ubuntu 18.04 (Vagrant and OVH)

### Scenario:
Firewall resource not idempotent. The following recipe:
```
firewall 'default' do
  action :install
end

firewall_rule 'Allow the world to ssh' do
    port 22
    command :allow
end
```
Generate always one updated resource:
```
       Recipe: ipt-firewall::default
         * firewall[default] action install
           * apt_package[ufw] action install (up to date)
           * template[/etc/default/ufw] action create (up to date)
            (up to date)
         * apt_package[ufw] action nothing (skipped due to action :nothing)
         * template[/etc/default/ufw] action nothing (skipped due to action :nothing)
         * firewall_rule[Allow the world to ssh] action create

         * firewall[default] action restart
           * file[/etc/default/ufw-chef.rules] action create (up to date)
            (up to date)

       Running handlers:
       Running handlers complete
       Chef Client finished, 1/8 resources updated in 02 seconds
```

### Steps to Reproduce:
Create a simple cookbook with the recipe above. Execute chef-client twice. 

### Expected Result:
At the 2nd run, no resource should be updated as the firewall is correctly configured.

### Actual Result:
At the 2nd run, one resource is still updated.

Thanks for your help on this.

**Comment by martinb3** [comment]
Hi there -- that resource is using the accumulator design pattern. It's action is simply adding to an array of rules, to build the full firewall ruleset. There's not really a concept of idempotency when looking at a single firewall rule -- it doesn't exist / isn't managed in isolation.

**Comment by DeWaRs1206** [comment]
So it means if my cookbook manage 20 firewall rules, at each run I would have 20 resources updated despite the fact nothing actually change on the system. Do I understand correctly your statement?

**Comment by martinb3** [comment]
@DeWaRs1206 -- yes, that's correct. It's quite, quite common to see resources that don't map perfectly to system objects (reboot, line, etc).

**Comment by DeWaRs1206** [comment]
Thanks for the quick answer martinb3.
