### ISSUE TITLE
Chef::Provider::FirewallRuleIptables does not work as advertised in README for allowing specific protocols

### ISSUE THREAD

**Issue by n8gard** [chef-cookbooks/firewall#95]
The README shows the ability to specify a raw protocol when using UFW via a specified provider as excepted here:
```
# use the iptables provider to specify protocol number on debian/ubuntu
firewall_rule 'vrrp' do
  provider    Chef::Provider::FirewallRuleIptables
  protocol    112
  command      :allow
end
```
This does not work and throws a compile-time error saying that only :tcp, :udp, :icmp or :none are valid protocol options.

I've had to drop down to using the 'execute' resource to specify iptables commands to allow VRRP (protocol 112) multicast. If this functionality could exist, I would be very happy.

**Comment by martinb3** [comment]
Hi there -- are you on an older version of the cookbook? The error message that's current in master is:
> must be either :tcp, :udp, :icmp, :none, or a valid IP protocol number

**Comment by martinb3** [comment]
Closing for lack of update.
